write_mode                 = "Overwrite"
reorder_imports            = true
reorder_imported_names     = true
reorder_imports_in_group   = true
condense_wildcard_suffices = true
use_try_shorthand          = true
normalize_comments         = true
fn_call_width              = 160
wrap_comments              = true
